Modified make_environment_tar and make_executable_tar to give tar files with everything already in place - just need to be extracted; modified Finstall to handle the new format of these tar files; added the install, install_env, and install_exes targets to Makefile to create then extract these tar files into INSTALL_FER_DIR given in site_specific.mk
git-svn-id: file:///home/users/tmap/svn/repos/ferret/trunk@12629 fdbf22ae-c210-0410-be80-ca943da6b8f8

diff --git a/bin/Finstall b/bin/Finstall
--- a/bin/Finstall
+++ b/bin/Finstall
@@ -5,8 +5,10 @@
 ## 1) modifies 'ferret_paths template' to specify locations of ferret
 ##    software and demo data sets and places the result in the indicated
 ##    sourcing directory as 'ferret_paths'
-## 2) installs ferret and gksm2ps executables and shared-object external
-##    functions from tar file to $FER_DIR/bin
+## 2) extracts the contents of fer_executables.tar.gz into $FER_DIR
+##    after renaming any existing files that would have been overwritten
+## All changes are recorded, with a timestamp, in the log file
+## $FER_DIR/bin/Finstall.log
 
 
 ### Assign $fer_dir, the desired FER_DIR value
@@ -17,7 +19,7 @@ get_fer_dir() {
         echo " The environment variable FER_DIR is currently defined as "
         echo " '${FER_DIR}' "
         echo " This is the directory where the 'fer_environment.tar.gz' "
-        echo " file was installed. "
+        echo " file was installed/extracted. "
         echo " "
         read -p " Is that correct and acceptable (y/n) [y] " ans
         if [ -z "${ans}" ] || [ "${ans}" = "Y" ] || [ "${ans}" = "y" ]; then
@@ -28,8 +30,8 @@ get_fer_dir() {
     until [ 0 = 1 ]; do
         echo " "
         echo " Enter the name of the directory where the 'fer_environment.tar.gz' "
-        echo " file was installed (FER_DIR).  The location recommended in the "
-        echo " Ferret installation guide was '/usr/local/ferret'. "
+        echo " file was installed/extracted (FER_DIR).  The location recommended "
+        echo " in the Ferret installation guide was '/usr/local/ferret'. "
         echo " "
         read -p " FER_DIR --> " fer_dir
         if [ ! -d "${fer_dir}" ]; then
@@ -58,7 +60,7 @@ get_fer_dsets() {
         echo " The environment variable FER_DSETS is currently defined as "
         echo " '${FER_DSETS}' "
         echo " This is the directory where the 'fer_dsets.tar.gz' file was "
-        echo " installed."
+        echo " installed/extracted."
         echo " "
         read -p " Is that correct and acceptable (y/n) [y] " ans
         if [ -z "${ans}" ] || [ "${ans}" = "Y" ] || [ "${ans}" = "y" ]; then
@@ -69,7 +71,7 @@ get_fer_dsets() {
     until [ 0 = 1 ]; do
         echo " "
         echo " Enter the name of the directory where the 'fer_dsets.tar.gz' "
-        echo " file was installed (FER_DSETS)."
+        echo " file was installed/extracted (FER_DSETS)."
         echo " "
         read -p " FER_DSETS --> " fer_dsets
         if [ ! -d "${fer_dsets}" ]; then
@@ -136,14 +138,42 @@ get_ferpaths_dir() {
 }
 
 
+### Write a message to ${fer_dir}/bin/Finstall.log (creating it if it does not exist)
+write_log_message() {
+#   Sanity check
+    if [ -z "${fer_dir}" ]; then
+        echo " Unexpected script error: fer_dir not defined in write_log_message "
+        exit 1
+    fi
+#   get_fer_dir ensures ${fer_dir}/bin already exists
+#   Create Finstall.log file if it does not exist
+    logfile="${fer_dir}/bin/Finstall.log"
+    if [ ! -f "${logfile}" ]; then
+        echo " Creating Finstall.log in ${fer_dir}/bin "
+        timestamp=`/bin/date +' %D %T'`
+        if ! echo "${timestamp} Created Finstall.log " > "${logfile}" ; then
+            return 1
+        fi
+    fi
+
+    timestamp=`/bin/date +' %D %T'`
+    if ! echo "${timestamp} $1 " >> "${logfile}" ; then
+        return 1
+    fi
+}
+
+
 ### Edit the ferret_paths_template.{csh,sh} files to create the ferret_paths.{csh,sh} files
 create_ferret_paths() {
 #   Check for existing ferret_paths.csh
     if [ -f "${ferpaths_dir}/ferret_paths.csh" ]; then
-        mv -f "${ferpaths_dir}/ferret_paths.csh" "${ferpaths_dir}/ferret_paths.csh.old"
-        echo " "
-        echo " Existing ${ferpaths_dir}/ferret_paths.csh "
-        echo " moved to ${ferpaths_dir}/ferret_paths.csh.old "
+        if mv -f "${ferpaths_dir}/ferret_paths.csh" "${ferpaths_dir}/ferret_paths.csh.old"; then
+            echo " "
+            echo " Renamed existing ${ferpaths_dir}/ferret_paths.csh "
+            echo "               to ${ferpaths_dir}/ferret_paths.csh.old "
+            write_log_message "Renamed existing ${ferpaths_dir}/ferret_paths.csh"
+            write_log_message "              to ${ferpaths_dir}/ferret_paths.csh.old"
+        fi
     fi
 #   Create new ferret_paths.csh
     if sed -e "/setenv FER_DIR/c\\
@@ -154,16 +184,21 @@ setenv FER_DSETS \"${fer_dsets}\"" \
            > "${ferpaths_dir}/ferret_paths.csh" ; then
         echo " "
         echo " Created ${ferpaths_dir}/ferret_paths.csh "
+        write_log_message "Created ${ferpaths_dir}/ferret_paths.csh"
     else
         echo " "
         echo " Unable to create ${ferpaths_dir}/ferret_paths.csh "
+        write_log_message "Unable to create ${ferpaths_dir}/ferret_paths.csh"
     fi
 #   Check for existing ferret_paths.sh
     if [ -f "${ferpaths_dir}/ferret_paths.sh" ]; then
-        mv -f "${ferpaths_dir}/ferret_paths.sh" "${ferpaths_dir}/ferret_paths.sh.old"
-        echo " "
-        echo " Existing ${ferpaths_dir}/ferret_paths.sh "
-        echo " moved to ${ferpaths_dir}/ferret_paths.sh.old "
+        if mv -f "${ferpaths_dir}/ferret_paths.sh" "${ferpaths_dir}/ferret_paths.sh.old"; then
+            echo " "
+            echo " Renamed existing ${ferpaths_dir}/ferret_paths.sh "
+            echo "               to ${ferpaths_dir}/ferret_paths.sh.old "
+            write_log_message "Renamed existing ${ferpaths_dir}/ferret_paths.sh"
+            write_log_message "              to ${ferpaths_dir}/ferret_paths.sh.old"
+        fi
     fi
 #   Create new ferret_paths.sh
     if sed -e "/export FER_DIR=/c\\
@@ -174,36 +209,83 @@ export FER_DSETS=\"${fer_dsets}\"" \
            > "${ferpaths_dir}/ferret_paths.sh" ; then
         echo " "
         echo " Created ${ferpaths_dir}/ferret_paths.sh "
+        write_log_message "Created ${ferpaths_dir}/ferret_paths.sh"
     else
         echo " "
         echo " Unable to create ${ferpaths_dir}/ferret_paths.sh"
+        write_log_message "Unable to create ${ferpaths_dir}/ferret_paths.sh"
     fi
 #   Check for existing ferret_paths
     if [ -f "${ferpaths_dir}/ferret_paths" ]; then
-        mv -f "${ferpaths_dir}/ferret_paths" "${ferpaths_dir}/ferret_paths.old"
-        echo " "
-        echo " Existing ${ferpaths_dir}/ferret_paths "
-        echo " moved to ${ferpaths_dir}/ferret_paths.old "
+        if mv -f "${ferpaths_dir}/ferret_paths" "${ferpaths_dir}/ferret_paths.old"; then
+            echo " "
+            echo " Renamed existing ${ferpaths_dir}/ferret_paths "
+            echo "               to ${ferpaths_dir}/ferret_paths.old "
+            write_log_message "Renamed existing ${ferpaths_dir}/ferret_paths"
+            write_log_message "              to ${ferpaths_dir}/ferret_paths.old"
+        fi
+    fi
+#   Check for existing ferret7
+    if [ -f "${fer_dir}/bin/ferret7" ]; then
+        if mv -f "${fer_dir}/bin/ferret7" "${fer_dir}/bin/ferret7.old"; then
+            echo " "
+            echo " Renamed existing ${fer_dir}/bin/ferret7 "
+            echo "               to ${fer_dir}/bin/ferret7.old "
+            write_log_message "Renamed existing ${fer_dir}/bin/ferret7"
+            write_log_message "              to ${fer_dir}/bin/ferret7.old"
+        fi
     fi
 #   Copy the appropriate file
-#   Note: $SHELL may not be defined in bash
+#   Note: $SHELL may not be defined in a Bourne-type shell
     if echo "${SHELL}" | grep -q 'csh$' ; then
         if ( cd "${ferpaths_dir}" ; ln -s "ferret_paths.csh" "ferret_paths" ) ; then
             echo " "
             echo " Created ${ferpaths_dir}/ferret_paths "
-            echo " as a link to ${ferpaths_dir}/ferret_paths.csh "
+            echo "     as a link to ferret_paths.csh "
+            write_log_message "Created ${ferpaths_dir}/ferret_paths"
+            write_log_message "    as a link to ferret_paths.csh"
         else
             echo " "
             echo " Unable to create ${ferpaths_dir}/ferret_paths "
+            write_log_message "Unable to create ${ferpaths_dir}/ferret_paths"
+        fi
+        if [ -f "${fer_dir}/bin/ferret7.csh" ]; then
+            if ( cd "${fer_dir}/bin" ; ln -s "ferret7.csh" "ferret7" ) ; then
+                echo " "
+                echo " Created ${fer_dir}/bin/ferret7 "
+                echo "     as a link to ferret7.csh "
+                write_log_message "Created ${fer_dir}/bin/ferret7"
+                write_log_message "    as a link to ferret7.csh"
+            else
+                echo " "
+                echo " Unable to create ${fer_dir}/bin/ferret7 "
+                write_log_message "Unable to create ${fer_dir}/bin/ferret7"
+            fi
         fi
     else
         if ( cd "${ferpaths_dir}" ; ln -s "ferret_paths.sh" "ferret_paths" ) ; then
             echo " "
             echo " Created ${ferpaths_dir}/ferret_paths "
-            echo " as a link to ${ferpaths_dir}/ferret_paths.sh "
+            echo "     as a link to ferret_paths.sh "
+            write_log_message "Created ${ferpaths_dir}/ferret_paths"
+            write_log_message "    as a link to ferret_paths.sh"
         else
             echo " "
             echo " Unable to create ${ferpaths_dir}/ferret_paths "
+            write_log_message "Unable to create ${ferpaths_dir}/ferret_paths"
+        fi
+        if [ -f "${fer_dir}/bin/ferret7.sh" ]; then
+            if ( cd "${fer_dir}/bin" ; ln -s "ferret7.sh" "ferret7" ) ; then
+                echo " "
+                echo " Created ${fer_dir}/bin/ferret7 "
+                echo "     as a link to ferret7.sh "
+                write_log_message "Created ${fer_dir}/bin/ferret7"
+                write_log_message "    as a link to ferret7.sh"
+            else
+                echo " "
+                echo " Unable to create ${fer_dir}/bin/ferret7 "
+                write_log_message "Unable to create ${fer_dir}/bin/ferret7"
+            fi
         fi
     fi
 }
@@ -213,7 +295,7 @@ export FER_DSETS=\"${fer_dsets}\"" \
 get_ferexec_dir() {
     until [ 0 = 1 ]; do
         echo " "
-        echo " Enter the name of the directory where containing the "
+        echo " Enter the name of the directory containing the "
         echo " 'fer_executables.tar.gz file. "
         read -p " 'fer_executables.tar.gz' location --> " ferexec_dir
         if [ ! -d "${ferexec_dir}" ]; then
@@ -233,97 +315,51 @@ get_ferexec_dir() {
 }
 
 
-### Install the contents of $ferexec_dir/fer_executables.tar.gz into
-### the appropriate subdirectories of $fer_dir
+### Install the contents of $ferexec_dir/fer_executables.tar.gz into $fer_dir
 install_execs() {
-#   Create Finstall.log file if it does not exist
-    logfile="${fer_dir}/bin/Finstall.log"
-    echo " "
-    if [ ! -f "${logfile}" ]; then
-        echo " Creating Finstall.log in ${fer_dir}/bin "
-        timestamp=`/bin/date +' %D %T'`
-        if ! echo "${timestamp} Created Finstall.log " > "${logfile}" ; then
-            return 1
-        fi
+    write_log_message "Installing/updating from ${ferexec_dir}/fer_executables.tar.gz"
+
+#   Get the list of files in the tar file
+    exetar_files=`tar tzf ${ferexec_dir}/fer_executables.tar.gz`
+    if [ -z "${exetar_files}" ]; then
+#        tar should have already printed a more appropriate error message
+         echo " No files found in ${ferexec_dir}/fer_executables.tar.gz "
+         write_log_message "No files found in ${ferexec_dir}/fer_executables.tar.gz"
+         return 1
     fi
 
-    timestamp=`/bin/date +' %D %T'`
-    if ! echo "${timestamp} Installing/updating from ${ferexec_dir}/fer_executables.tar.gz " >> "${logfile}" ; then
-        return 1
+#   Make sure the tar file is the right format
+    lib_files=`tar tzf ${ferexec_dir}/fer_executables.tar.gz lib`
+    if [ -z "${lib_files}" ]; then
+         echo " Aborting - old style fer_executables.tar.gz "
+         write_log_message "Aborting - old style fer_executables.tar.gz"
+         return 1
     fi
 
-#   The list of files - ferret* and gksm2ps - that will be going in $fer_dir/bin
-    ferbin_files=`tar tzf ${ferexec_dir}/fer_executables.tar.gz --wildcards ferret\* gksm2ps 2> /dev/null`
-#   Rename old executables if they exist
-    for binfile in ${ferbin_files} ; do
-        if [ -f "${fer_dir}/bin/${binfile}" ]; then
-            if mv -f "${fer_dir}/bin/${binfile}" "${fer_dir}/bin/${binfile}.old" ; then
-                echo " Renamed existing ${binfile} to ${binfile}.old "
-                timestamp=`/bin/date +' %D %T'`
-                echo "${timestamp} Renamed existing ${binfile} to ${binfile}.old " >> "${logfile}"
+#   Rename old files if they exist
+    echo " Renaming (by appending '.old') any existing files in ${fer_dir} "
+    echo "     that will be replaced by files in ${ferexec_dir}/fer_executables.tar.gz "
+    for exefile in ${exetar_files} ; do
+        if [ -f "${fer_dir}/${exefile}" ]; then
+            if mv -f "${fer_dir}/${exefile}" "${fer_dir}/${exefile}.old" ; then
+                write_log_message "Renamed existing ${exefile} to ${exefile}.old"
             else
+                echo " Aborting - unable to rename ${fer_dir}/${exefile} "
+                write_log_message "Aborting - unable to rename ${exefile}"
                 return 1
             fi
         fi
     done
-#   Check if there are any files to go into $fer_dir/bin
-    if [ -n "${ferbin_files}" ]; then
-#       $fer_dir/bin guaranteed to exist by get_fer_dir()
-#       Extract these files into $fer_dir/bin
-        if ( cd "${fer_dir}/bin" ; tar xzf "${ferexec_dir}/fer_executables.tar.gz" ${ferbin_files} ) ; then
-            timestamp=`/bin/date +' %D %T'`
-            for binfile in ${ferbin_files} ; do
-                echo " Extracted ${binfile} to ${fer_dir}/bin "
-                echo "${timestamp} Extracted ${binfile} to ${fer_dir}/bin " >> "${logfile}"
-            done
-        else
-            return 1
-        fi
-    fi
 
-#   The list of files - *.so - that will be going in $fer_dir/ext_func/libs
-    feref_files=`tar tzf ${ferexec_dir}/fer_executables.tar.gz --wildcards \*.so 2> /dev/null`
-#   Don't bother renaming existing files
-#   Check if there are any external function files provided
-    if [ -n "${feref_files}" ]; then
-#       Make sure ${fer_dir}/ext_func/libs exists
-        if ! mkdir -p "${fer_dir}/ext_func/libs" ; then
-            return 1
-        fi
-#       Extract these files into $fer_dir/ext_func/libs
-        if ( cd "${fer_dir}/ext_func/libs" ; tar xzf "${ferexec_dir}/fer_executables.tar.gz" ${feref_files} ) ; then
-            timestamp=`/bin/date +' %D %T'`
-            echo " Extracted external function files to ${fer_dir}/ext_func/libs "
-            echo " For more details, see '${timestamp}' entries in the log file "
-            echo " ${logfile} "
-            for effile in ${feref_files} ; do
-                echo "${timestamp} Extracted ${effile} to ${fer_dir}/ext_func/libs " >> "${logfile}"
-            done
-        else
-            return 1
-        fi
-    fi
-
-#   The list of files that will be going in $fer_dir/lib
-    ferlib_files=`tar tzf ${ferexec_dir}/fer_executables.tar.gz lib 2> /dev/null`
-#   Don't bother renaming existing files
-#   Check if there are any lib files provided
-    if [ -n "${ferlib_files}" ]; then
-#       Make sure ${fer_dir}/lib exists
-        if ! mkdir -p "${fer_dir}/lib" ; then
-            return 1
-        fi
-#       Extract the lib files into $fer_dir
-        if ( cd "${fer_dir}" ; tar xzf "${ferexec_dir}/fer_executables.tar.gz" ${ferlib_files} ) ; then
-            timestamp=`/bin/date +' %D %T'`
-            echo " Extracted lib files to ${fer_dir}/lib "
-            echo " For more details, see '${timestamp}' entries in the log file ${logfile} "
-            for libfile in ${ferlib_files} ; do
-                echo "${timestamp} Extracted ${libfile} to ${fer_dir}/lib " >> "${logfile}"
-            done
-        else
-            return 1
-        fi
+#   Extract the files into $fer_dir
+    echo " Extracting files from ${ferexec_dir}/fer_executables.tar.gz "
+    echo "                    to ${fer_dir} "
+    if ( cd "${fer_dir}" ; tar xzf "${ferexec_dir}/fer_executables.tar.gz" ) ; then
+        for exefile in ${exetar_files} ; do
+            write_log_message "Extracted ${exefile}"
+        done
+    else
+        return 1
     fi
 }
 
@@ -334,7 +370,7 @@ echo " "
 echo " This script can do two things for you to help install Ferret: "
 echo " "
 echo " (1) Install the Ferret executables into FER_DIR/bin from the "
-echo "     compressed .gz file you got (usually) via ftp."
+echo "     fer_executables.tar.gz file."
 echo " "
 echo "     You will want to run this option if you are installing "
 echo "     Ferret for the first time or if you are updating Ferret "
diff --git a/bin/make_executable_tar b/bin/make_executable_tar
--- a/bin/make_executable_tar
+++ b/bin/make_executable_tar
@@ -1,52 +1,187 @@
-#! /bin/csh -x
-# make_executable_tar
-# ver 1.0 5/99 *kob* 
+#! /bin/csh
 
-# this script encourages the tar file producer to make several manual
-# sanity checks but it does not enforce behavior
+# mycp needs to recursively copy subdirectories for the lib/python* directories
+# verbose flag used to create info messages when running this script
+set mycp = "/bin/cp -v -r --preserve=timestamp"
+set mylns = "/bin/ln -v -s"
 
-if ( $#argv == 1 ) then
-   set targ_dist_parent = $argv[1]
-   set bin_dir = $targ_dist_parent
-else
-   echo usage:
-   echo "         make_environment_tar binary_area machine_type "
-   echo e.g. "'make_executable_tar /home/users/ansley/ferret_install_utilities/bin'"
-   echo will make a gzipped tar file with the Ferret executables that are 
-   echo in the /home/users/ansley/ferret_install_utilities/bin directory  
-   exit 0
+echo ""
+if ( $#argv == 3 ) then
+    if ( "$3" == "-y" ) then
+        set auto_ans = "y"
+    endif
+endif
+if ( ($#argv < 2) || ($#argv > 3) || \
+     (($#argv == 3) && (! $?auto_ans)) ) then
+   echo "Usage:  $0  <ferret_dir>  <target_dir>  [ -y ] "
+   echo ""
+   echo "    Creates the Ferret installation file fer_executables.tar.gz. "
+   echo "    The required files will be copied from the ferret source directory "
+   echo "    <ferret_dir>, in which ferret or pyferret, gksm2ps, and the font files "
+   echo "    have been built.  All the files required will be copied to a temporary "
+   echo "    directory which this script will create.  Any missing executables will "
+   echo "    be noted.  The gzipped tar file fer_executables.tar.gz will be written "
+   echo "    in <target_dir>, which must already exist.  If the optional third "
+   echo "    argument '-y' is given, any questions normally asked by the script "
+   echo "    will be automatically answered with 'y'. "
+   echo ""
+   exit 1
 endif
 
-cd $bin_dir
+if ( ! -d "$1" ) then
+   echo "$1 does not exist or is not a directory"
+   echo ""
+   exit 1
+endif
+set ferret_dir = `cd "$1" ; pwd`
+if ( ! -d "$2" ) then
+   echo "$2 does not exist or is not a directory"
+   echo ""
+   exit 1
+endif
+set target_dir = `cd "$2" ; pwd`
 
-# get tar file location
-echo "Enter directory path to create the gzipped tar file in"
-set ans = $<
-set ctar_file = $ans/fer_executables.tar
-echo "Ready to create gzipped tar file $ctar_file"
-ready:
-echo "OK to continue ?"
-set ans = $<
-switch($ans)
-case y:
-   breaksw
-case n:
-   exit 0
-default:
-   echo "must answer y or n"
-   goto ready
-endsw
+set pyferret_dir = "${ferret_dir}/pyferret_install"
+if ( ! -d "${pyferret_dir}" ) then
+   echo "${pyferret_dir} does not exist or is not a directory"
+   echo "    pyferret module not created"
+   echo ""
+   set pyferret_dir = ""
+endif
 
-# make the gzipped tar file
-rm -f .tar_create_log
-tar vcf $ctar_file * >& $bin_dir/.tar_create_log
+# Get the version of ferret recorded in the code
+set version = `awk '/revision_level/ {print $4}' ${ferret_dir}/fer/dat/xrevision_data.F`
+if ( ($status != 0) || ("${version}" == "") ) then
+   echo "Unable to read the version number from xrevision_data.F in ${ferret_dir}/fer/dat"
+   echo ""
+   exit 1
+endif
+echo "Ferret version number is ${version}"
+echo ""
 
-gzip $ctar_file
+# Make a clean temporary directory for the tar file contents
+set temp_dir = "/var/tmp/fer_exe_$$"
+rm -fr ${temp_dir}
+mkdir ${temp_dir}
 
-ls -l $ctar_file.*
-echo "If there are any problems w/ the tar file, see "$bin_dir/".tar_create_log for"
-echo "more information"
+mkdir ${temp_dir}/bin
 
+# Copy fer/ferret_c
+if ( -x ${ferret_dir}/fer/ferret_c ) then
+   ${mycp} ${ferret_dir}/fer/ferret_c ${temp_dir}/bin/ferret_v${version}
+   cd ${temp_dir}/bin
+   ${mylns} ferret_v${version} ferret
+else
+   echo "No ferret_c executable found in ${ferret_dir}/fer"
+#  An error only if pyferret_dir was not given
+   if ( "${pyferret_dir}" == "" ) then
+      echo ""
+      exit 1
+   else
+      echo "   ferret_v<n> and ferret symbolic link not created"
+      echo ""
+   endif
+endif
 
+# Copy the external function shared-object library files
+mkdir -p ${temp_dir}/ext_func/libs
+# If pyferret, do not copy the .so files at this time due to pyferret bug
+if ( "${pyferret_dir}" == "" ) then
+   find ${ferret_dir}/external_functions -type f -perm -100 -name \*.so -exec ${mycp} {} ${temp_dir}/ext_func/libs \;
+endif
 
+# Copy gksm2ps/gksm2ps
+if ( ! -x ${ferret_dir}/gksm2ps/gksm2ps ) then
+   echo "No gksm2ps executable found in ${ferret_dir}/gksm2ps"
+   echo ""
+   exit 1
+endif
+${mycp} ${ferret_dir}/gksm2ps/gksm2ps ${temp_dir}/bin/gksm2ps
+
+# Copy font files from bin/build_fonts/unix/
+set fer_files = ${ferret_dir}/bin/build_fonts/unix/f*
+if ( ($status != 0) || ("${fer_files}" == "") ) then
+   echo "No font files found in ${ferret_dir}/bin/build_fonts/unix"
+   echo ""
+   exit 1
+endif
+mkdir ${temp_dir}/ppl
+mkdir ${temp_dir}/ppl/fonts
+${mycp} ${fer_files} ${temp_dir}/ppl/fonts
+
+# Copy fer/threddsBrowser/threddsBrowser.jar
+set tb_jar = ${ferret_dir}/fer/threddsBrowser/threddsBrowser.jar
+if ( ! -r ${tb_jar} ) then
+   echo "No threddsBrowser.jar file found ${ferret_dir}/fer/threddsBrowser"
+   echo ""
+   exit 1
+endif
+mkdir ${temp_dir}/lib
+${mycp} ${tb_jar} ${temp_dir}/lib
+
+# Either copy fer/threddsBrowser/toolsUI/toolsUI-4.1.jar ...
+set toolsui_jar = ${ferret_dir}/fer/threddsBrowser/toolsUI/toolsUI-4.1.jar
+if ( ! -r ${toolsui_jar} ) then
+   echo "No toolsUI-4.1.jar file found ${ferret_dir}/fer/threddsBrowser/toolsUI"
+   echo ""
+   exit 1
+endif
+${mycp} ${toolsui_jar} ${temp_dir}/lib
+# ... or print a message about how to get toolsUI-4.1.jar
+# echo "To minimize size, the toolsUI-4.1.jar file is not included."
+# echo "The user needs to download the jar file from:"
+# echo "  ftp://ftp.unidata.ucar.edu/pub/netcdf-java/v4.1/toolsUI-4.1.jar"
+# echo "(or we can just grab it from <ferret_dir>/fer/threddsBrowser/toolsUI/)"
+# echo 'and put it under the $FER_LIBS ($FER_DIR/lib) subdirectory'
+
+# Create a symbolic link to a (possibly non-existant) toolsUI-4.1.jar file
+cd ${temp_dir}/lib
+${mylns} toolsUI-4.1.jar toolsUI.jar
+
+# Copy pyferret files
+if ( "${pyferret_dir}" != "" ) then
+   set python_dirs = ${pyferret_dir}/lib/python*
+   if ( ($status != 0) || ("${python_dirs}" == "") ) then
+      echo "No python* directories found in ${pyferret_dir}/lib"
+      echo ""
+      exit 1
+   endif
+   ${mycp} ${python_dirs} ${temp_dir}/lib
+endif
+
+# Create the tar file
+set ctar_file = "${target_dir}/fer_executables.tar.gz"
+echo ""
+echo "The tar file will be created from the contents of "
+echo "${temp_dir}"
+echo "(which can now be examined or tweaked from another shell/window)"
+echo ""
+echo -n "Create gzipped tar file ${ctar_file} (y/n)? "
+if ( $?auto_ans ) then
+    set ans = "${auto_ans}"
+else
+    set ans = $<
+endif
+while ( ("${ans}" != "y") && ("${ans}" != "n") )
+   echo -n "Answer either y or n: "
+   set ans = $<
+end
+if ( "${ans}" == "y" ) then
+   echo ""
+   cd ${temp_dir}
+   rm -f "${ctar_file}"
+   tar cvzf "${ctar_file}" *
+   echo ""
+   ls -l "${ctar_file}"
+else
+   echo ""
+   echo "Tar file NOT created"
+endif
+
+# Clean up
+echo ""
+echo "Cleaning up - removing ${temp_dir}"
+cd "${target_dir}"
+rm -fr "${temp_dir}"
+echo ""
 
