Converting csh scripts to bash scripts in pyferret branch
git-svn-id: file:///home/users/tmap/svn/repos/ferret/branches/pyferret@12080 fdbf22ae-c210-0410-be80-ca943da6b8f8

diff --git a/bin/Fprint_template b/bin/Fprint_template
--- a/bin/Fprint_template
+++ b/bin/Fprint_template
@@ -1,4 +1,4 @@
-#! /bin/csh -f
+#! /bin/sh
 # Fprint
 # Script to translate metafiles generated by Ferret.  It runs either gksm2ps
 # (on systems where Ferret uses xgks -- releases after Mar 1994), or mtt;
@@ -30,224 +30,16 @@
 
 # 12.15.94 Due to a bug in the DEC OSF lpr command, use of the -s (symbolic
 # link, ie, don't copy the file -- used with large files) with the -r option
-# (remove file after printing) cannot be done.  The file is deleted before it 
-# printed.  Consequently for OSF machines, I have dropped the use of the -r 
+# (remove file after printing) cannot be done.  The file is deleted before it
+# printed.  Consequently for OSF machines, I have dropped the use of the -r
 # option and the print files will accumulate.
 
-
-set err_txt = "no_err"
-if ($#argv == 0 || "$argv" == "-h" || "$argv" == "-help") goto help
-
-touch Fprint_output0.ps
-rm -f Fprint_output*.ps
-
-set output_args   	= " "
-set output        	= "printer"
-set printer_named	= 0
-set translator_args  	= "-l cps -d cps"
-
-set gksm2ps_files 	= ""
-set mtt_files		= ""
-set got_gksm2ps_files   = 0
-set got_mtt_files	= 0		
-
-set REMOVE = "-r"
-
-# Pick off arguments til the end of argv
-while ($#argv != 0)
-   switch ($argv[1])
-      case -P:
-#        Send output to named printer  
-	 shift argv      
-
-	 set err_txt = "-P $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 set output_args = "$output_args -P$argv[1]"
-	 set output = "printer"
-
-	 set fprinter = $argv[1]
-	 set printer_named = 1
-         shift argv
-
-	 breaksw
-      case -o:
-#	 Output is to be directed to plot file and not printed
-	 shift argv
-      
- 	 set err_txt = "-o $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 set translator_args = "$translator_args -o $argv[1]"
-	 set output = "file"
-         shift argv
-
-	 breaksw
-      case -X:
-#	 Output is to be directed to Xwindow
-	 shift argv
- 	 set translator_args = ""
-	 set output = "Xwindow"
-
-	 breaksw
-      case -#:
-#        Print N copies 
-	 set output_args = "$output_args $argv[1]" 
-	 shift argv      
-
-	 set err_txt = "-# $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 set output_args = "$output_args$argv[1]"
-         shift argv
-
-	 breaksw
-      case -p:
-#	 Page orientation: landscape or portrait
-	 shift argv
-	 
-	 set err_txt = "-p $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 if ($argv[1] != "landscape" && $argv[1] != "portrait") goto help
-
-	 set translator_args = "$translator_args -p $argv[1]"
-         shift argv
-
-	 breaksw
-      case -l:
-#	 Line color: cps (color) or ps (b&w)
-	 shift argv
-      
-	 set err_txt = "-l $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 if ($argv[1] != "cps" && $argv[1] != "ps") goto help
-
-	 set translator_args = "$translator_args -l $argv[1]"
-         shift argv
-
-	 breaksw
-      case -d:
-#	 Supported devices: cps (color PostScript) or phaser (TEK phaser ps)
-	 shift argv
-      
-	 set err_txt = "-d $argv[1]"
-	 if (`echo $argv[1] | cut -c1` == "-") goto help
-	 if ($argv[1] != "cps" && $argv[1] != "phaser") goto help
-
-	 set translator_args = "$translator_args -d $argv[1]"
-         shift argv
-
-	 breaksw
-      case -R:
-#	 Don't append to metafiles with date stamp when translation is complete
-	 set translator_args = "$translator_args -R"
-	 shift argv
-
-	 breaksw
-      case -C:
-#	 Use CMYK color model 
-	 set translator_args = "$translator_args -C"
-	 shift argv
-
-	 breaksw
-      default:
-	 # Everything else is passed to translator -- gotta be a file
-	 if (! -e $argv[1]) then
-	   echo "ERROR: $argv[1] is not a file name"
-	   goto help
-	 endif
-
-	 head -n 1 $argv[1] | grep -s ^GKSM > /dev/null
-
-	 if ($status == 0) then
-	   set gksm2ps_files     = "$gksm2ps_files $argv[1]"
-	   set got_gksm2ps_files = 1
-	 else	 
-	   set mtt_files         = "$mtt_files $argv[1]"
-	   set got_mtt_files     = 1	 
-	 endif
-
-         shift argv
-         breaksw
-   endsw
-end
-
-if ($output != "printer" || ! $printer_named) goto xeq_translator
-
-############################ MODIFY HERE ###################################
-
-# Now set device characteristics for named printers
-switch ($fprinter)
-case COLOR_PS:
-# If the printer is a color PS printer, use that device type
-   set translator_args = "$translator_args -l cps -d cps"
-   breaksw
-case PHASER_PX_TRANSFER:
-# BUT If the printer is a PHASER PX with transfer sheets, type is "phaser"
-   set translator_args = "$translator_args -l cps -d phaser"
-   breaksw
-# The following example printers take the default options mentioned above.
-case MONOCHROME_PS1:
-   breaksw
-case MONOCHROME_PS2:
-   breaksw
-case MONOCHROME_PS3:
-   breaksw
-default:
-# The named printer is not a valid choice:
-# This is the sort of message I anticipate the user getting if one names an
-# unsupported printer:
-#
-#   echo -n "'${fprinter}' is not a valid printer."
-#   if ($?PRINTER) then
-#     echo " The default printer is $PRINTER."
-#   else
-#     echo " "
-#   endif
-#   echo " Available printers are COLOR_PS, PHASER_PX_TRANSFER,"
-#   echo " MONOCHROME_PS1, MONOCHROME_PS2, and MONOCHROME_PS3"
-#
-# For now a user gets this message:
-   echo " "
-   echo " The Fprint script has not been set up to use the -P option"
-   echo " yet -- it should work with the default printer."
-   echo " "
-   exit
-endsw
-
-##################### END OF "MODIFY HERE" SECTION ##########################
-
-# Now process the metafile(s) and print the plot file if appropriate
-xeq_translator:
-if (`uname -s` == "OSF1") set REMOVE = ""
-switch ($output)
-case printer:
-   if ($got_gksm2ps_files) then
-      gksm2ps -o Fprint_output1$$.ps $translator_args $gksm2ps_files
-      if (-e Fprint_output1$$.ps) then
-         lpr -s ${REMOVE} $output_args ./Fprint_output1$$.ps
-      endif
-   endif
-
-   if ($got_mtt_files) then
-      mtt -o Fprint_output2$$.ps $translator_args $mtt_files
-      if (-e Fprint_output2$$.ps) then
-         lpr -s ${REMOVE} $output_args ./Fprint_output2$$.ps
-      endif
-   endif
-
-   breaksw
-case file:
-   if ($got_gksm2ps_files) gksm2ps $translator_args $gksm2ps_files 
-   if ($got_mtt_files)    mtt     $translator_args $mtt_files 
-   breaksw
-case Xwindow:
-   if ($got_gksm2ps_files) gksm2ps -X $gksm2ps_files 
-   if ($got_mtt_files) mtt $mtt_files
-
-   breaksw
-endsw
-exit
-
-help:
-   if ("$err_txt" != "no_err") echo "ERROR: You made a syntax error near $err_txt"
+print_usage() {
+   if [ -n "$err_txt" ]; then
+      echo " "
+      echo "ERROR: You made a syntax error near $err_txt"
+      echo " "
+   fi
    echo "Script to translate Ferret's graphics metafile(s) to PostScript"
    echo "usage: Fprint [-P printer || -o file_name || -X]"
    echo "              [-p landscape || portrait] [-# <number of copies>]"
@@ -260,9 +52,246 @@ help:
    echo "   -#: print more than one copy of the plots"
    echo "   -l: line styles, ps == monochrome, cps == color"
    echo "   -R: do not rename files with a date stamp appended (default is to stamp)"
-   echo "   -C: Output a CMYK postscript file (default is RGB)" 
+   echo "   -C: Output a CMYK postscript file (default is RGB)"
    echo "Examples: "
    echo "    Fprint metafile.plt*"
    echo "    Fprint -P our_color_printer -l cps -# 10 metafile.plt*"
    echo "    Fprint -p portrait -R metafile.plt.~2~"
+}
+
+if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ]; then
+   print_usage
    exit
+fi
+
+touch Fprint_output0.ps
+rm -f Fprint_output*.ps
+
+output_args=" "
+output="printer"
+printer_named=0
+translator_args="-l cps -d cps"
+
+gksm2ps_files=""
+mtt_files=""
+got_gksm2ps_files=0
+got_mtt_files=0
+
+REMOVE="-r"
+
+# Pick off arguments til the end of the arguments
+while [ $# != 0 ]; do
+   case "$1" in
+#     Send output to named printer
+      "-P")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-P $1"
+            print_usage
+            exit 1
+         fi
+         output_args="$output_args -P$1"
+         output="printer"
+         fprinter=$1
+         printer_named=1
+         shift
+         ;;
+#     Output is to be directed to plot file and not printed
+      "-o")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-o $1"
+            print_usage
+            exit 1
+         fi
+         translator_args="$translator_args -o $1"
+         output="file"
+         shift
+         ;;
+#     Output is to be directed to Xwindow
+      "-X")
+         shift
+         translator_args=""
+         output="Xwindow"
+         ;;
+#     Print N copies
+      "-#")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-# $1"
+            print_usage
+            exit 1
+         fi
+         output_args="$output_args -#$1"
+         shift
+         ;;
+#     Page orientation: landscape or portrait
+      "-p")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-p $1"
+            print_usage
+            exit 1
+         fi
+         if [ "$1" != "landscape" ] && [ "$1" != "portrait" ]; then
+            err_txt="-p $1"
+            print_usage
+            exit 1
+         fi
+         translator_args="$translator_args -p $1"
+         shift
+         ;;
+#     Line color: cps (color) or ps (b&w)
+      "-l")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-l $1"
+            print_usage
+            exit 1
+         fi
+         if [ "$1" != "cps" ] && [ "$1" != "ps" ]; then
+            err_txt="-l $1"
+            print_usage
+            exit 1
+         fi
+         translator_args="$translator_args -l $1"
+         shift
+         ;;
+#     Supported devices: cps (color PostScript) or phaser (TEK phaser ps)
+      "-d")
+         shift
+         val=`echo $1 | cut -c1`
+         if [ "$val" == "-" ]; then
+            err_txt="-d $1"
+            print_usage
+            exit 1
+         fi
+         if [ "$1" != "cps" ] && [ "$1" != "phaser" ]; then
+            err_txt="-d $1"
+            print_usage
+            exit 1
+         fi
+         translator_args="$translator_args -d $1"
+         shift
+         ;;
+#     Don't append to metafiles with date stamp when translation is complete
+      "-R")
+         translator_args="$translator_args -R"
+         shift
+         ;;
+#     Use CMYK color model
+      "-C")
+         translator_args="$translator_args -C"
+         shift
+         ;;
+#     Everything else is passed to translator -- gotta be a file
+      *)
+         if [ ! -f $1 ]; then
+            echo " "
+            echo "ERROR: $1 is not a file name"
+            echo " "
+            print_usage
+            exit 1
+         fi
+         if head -n 1 $1 | grep -q "^GKSM" ; then
+            gksm2ps_files="$gksm2ps_files $1"
+            got_gksm2ps_files=1
+         else
+            mtt_files="$mtt_files $1"
+            got_mtt_files=1
+         fi
+         shift
+         ;;
+   esac
+done
+
+if [ "$output" == "printer" ] && [ $printer_named -ne 0 ]; then
+
+############################ MODIFY HERE ###################################
+
+#    Now set device characteristics for named printers
+   case "$fprinter" in
+#     If the printer is a color PS printer, use that device type
+      "COLOR_PS")
+         translator_args="$translator_args -l cps -d cps"
+         ;;
+#     BUT If the printer is a PHASER PX with transfer sheets, type is "phaser"
+      "PHASER_PX_TRANSFER")
+         translator_args="$translator_args -l cps -d phaser"
+         ;;
+#     The following example printers take the default options mentioned above.
+      "MONOCHROME_PS1")
+         ;;
+      "MONOCHROME_PS2")
+         ;;
+      "MONOCHROME_PS3")
+         ;;
+#     The named printer is not a valid choice
+      *)
+#        This is the sort of message I anticipate the user getting
+#        if one names an unsupported printer:
+#
+#        echo -n "'${fprinter}' is not a valid printer."
+#        if [ -n "$PRINTER" ]; then
+#           echo " The default printer is $PRINTER."
+#        else
+#           echo " "
+#        endif
+#        echo " Available printers are COLOR_PS, PHASER_PX_TRANSFER,"
+#        echo " MONOCHROME_PS1, MONOCHROME_PS2, and MONOCHROME_PS3"
+#
+#        For now a user gets this message:
+         echo " "
+         echo " The Fprint script has not been set up to use the -P option"
+         echo " yet -- it should work with the default printer."
+         echo " "
+         exit
+   esac
+
+##################### END OF "MODIFY HERE" SECTION ##########################
+
+fi
+
+# Now process the metafile(s) and print the plot file if appropriate
+if [ `uname -s` == "OSF1" ]; then
+   REMOVE=""
+fi
+case $output in
+   "printer")
+      if [ $got_gksm2ps_files -ne 0 ]; then
+         gksm2ps -o Fprint_output1$$.ps $translator_args $gksm2ps_files
+         if [ -f Fprint_output1$$.ps ]; then
+            lpr -s ${REMOVE} $output_args ./Fprint_output1$$.ps
+         fi
+      fi
+
+      if [ $got_mtt_files -ne 0 ]; then
+         mtt -o Fprint_output2$$.ps $translator_args $mtt_files
+         if [ -f Fprint_output2$$.ps ]; then
+            lpr -s ${REMOVE} $output_args ./Fprint_output2$$.ps
+         fi
+      fi
+      ;;
+   "file")
+      if [ $got_gksm2ps_files -ne 0 ]; then
+         gksm2ps $translator_args $gksm2ps_files
+      fi
+      if [ $got_mtt_files -ne 0 ]; then
+         mtt $translator_args $mtt_files
+      fi
+      ;;
+   "Xwindow")
+      if [ $got_gksm2ps_files -ne 0 ]; then
+         gksm2ps -X $gksm2ps_files
+      fi
+      if [ $got_mtt_files -ne 0 ]; then
+         mtt $mtt_files
+      fi
+      ;;
+esac
+
