Updated bin/make_*_tar files, and some other clean-up, for creating distributables for pyferret
git-svn-id: file:///home/users/tmap/svn/repos/ferret/branches/pyferret@12400 fdbf22ae-c210-0410-be80-ca943da6b8f8

diff --git a/bin/make_environment_tar b/bin/make_environment_tar
--- a/bin/make_environment_tar
+++ b/bin/make_environment_tar
@@ -1,119 +1,111 @@
-#! /bin/csh -x
-# make_environment_tar
-# ver 1.0 4/94 *sh*
-# ver 2.0 5/99 *kob* massive upgrade to include CVS
-# ver 3.0 11/10 *acm* change from CVS to svn
+#! /bin/csh
 
-# this script encourages the tar file producer to make several manual
-# sanity checks but it does not enforce behavior
-
-#Make sure we are running on an OSF machine - only kind right now which can
-# run svn
-set thost = `uname -s`
-
-if ( $#argv == 2 ) then
-   set targ_dist_parent = $argv[1]
-   set machine_type = $argv[2]
-   set source_dir = $targ_dist_parent/$machine_type
-else
+echo ""
+if ( $#argv != 2 ) then
+   echo "Usage:  $0  <svn_repository>  <target_dir> "
    echo ""
-   echo usage:
-   echo make_environment_tar target_area machine_type
-   echo machine_type may be solaris, alpha, sgi, linux, x86_64-linux, or win32
-   echo e.g. "'make_environment_tar /home/users/ansley/ferret_install_utilities x86_64-linux'" will extract  
-   echo files for the Ferret environment in the directory
-   echo "'/home/users/ansley/ferret_install_utilities/x86_64-linux'"
-   echo and ask for a location to place the gzipped tar file
+   echo "    The required files will be extracted from <svn_repository> "
+   echo "    (e.g., 'file:///home/users/tmap/svn/repos/ferret/trunk') "
+   echo "    to a temporary directory which this script will create. "
+   echo "    Font files and lib files are NOT included in the tar file "
+   echo "    generated.  The gzipped tar file fer_environment.tar.gz "
+   echo "    will be written in <target_dir>, which must already exist. "
    echo ""
- exit 0
+   exit 1
 endif
 
-cd $source_dir
+set info = `svn info "$1"`
+if ( "${info}" == "" ) then
+#  svn has printed an appropriate error message
+#  (but still returned a zero status)
+   echo ""
+   exit 1
+endif
+set repository = "$1"
 
-#use svn now to checkout desired files
-echo "Extracting FERRET environment files......."
-svn checkout file:///home/users/tmap/svn/repos/ferret/trunk/bin >& .install_log
-svn checkout file:///home/users/tmap/svn/repos/ferret/trunk/jnls >>& .install_log
-svn checkout file:///home/users/tmap/svn/repos/ferret/trunk/external_functions >>& .install_log
-svn checkout file:///home/users/tmap/svn/repos/ferret/trunk/palettes >>& .install_log
-svn checkout file:///home/users/tmap/svn/repos/ferret/trunk/bin >>& .install_log
+if ( ! -d "$2" ) then
+   echo "$2 does not exist "
+   echo ""
+   exit 1
+endif
+# Make sure target_dir is a full pathname
+set target_dir = ` cd "$2" ; pwd`
 
-#Now move these files into the proper position
-echo "Doing a bit of rearranging now......."
+# Make a clean temporary directory for the tar file contents
+set temp_dir = "/var/tmp/fer_env_$$"
+rm -fr ${temp_dir}
+mkdir ${temp_dir}
+cd ${temp_dir}
+
+# Checkout the required files
+echo "Extracting FERRET environment files "
+echo "from ${repository} "
+echo "to ${temp_dir} "
+echo "   shell scripts"
+svn checkout -q ${repository}/bin
+echo "   journal files"
+svn checkout -q ${repository}/jnls
+echo "   external function source files"
+svn checkout -q ${repository}/external_functions
+echo "   palettes"
+svn checkout -q ${repository}/palettes
+
+# Move files into thier proper position
+echo "Doing a bit of rearranging"
 mv jnls/* .
 rm -rf jnls
 mv palettes ppl
 mkdir ext_func
 mv external_functions ext_func/src
 
+# Remove files that should not be distributed
+echo "Removing clutter"
+rm -f bin/Fapropos* >& /dev/null
+rm -f bin/Fhelp* >& /dev/null
+rm -f bin/Findex* >& /dev/null
+rm -f bin/Finstall.[^c]* >& /dev/null
+rm -f bin/Ftoc* >& /dev/null
+rm -f bin/ferret_paths*_template >& /dev/null
+rm -f bin/make_*_tar >& /dev/null
+rm -fr bin/fonts_* >& /dev/null
+rm -fr bin/build_fonts/original
 
-#Copy fonts
-echo "Copying fonts......."
-cd ppl >& /dev/null
-mkdir fonts
-cd fonts >& /dev/null
-if ($machine_type == linux || $machine_type == win32) then
-    cp -p /home/users/tmap/ferret/linux/ppl/fonts/f* .
-else
-    cp -p /home/users/tmap/ferret/x86_64-linux/ppl/fonts/f* .
-endif
-
-#cd ../.. >& /dev/null
-pwd
-cd ../.. 
-pwd
-
-# Now set up the proper soft links
-echo "Setting Up links......."
-# cd bin >& /dev/null
-cd bin 
+# Now set up the proper symbolic links
+echo "Setting up symbolic links"
+cd bin
 ln -s Fdescr Fdesc
 ln -s Fgrids Fgrid
 ln -s Fprint_template Fprint
+cd ..
 
-# Remove refs to old doc/ directory
-rm -f Fapropos*
-rm -f Fhelp*
-rm -f Findex*
-rm -f Ftoc*
-cd .. >& /dev/null
-
-pwd
-
-mkdir lib
-cd lib 
-cp $FER_DIR/lib/threddsBrowser.jar .
-cp $FER_DIR/lib/toolsUI-4.1.jar .
-ln -s toolsUI-4.1.jar toolsUI.jar
-cd ../
-
-# get tar file location
-echo "Enter directory path to create the gzipped tar file in"
+# Create the tar file
+set ctar_file = "${target_dir}/fer_environment.tar.gz"
+echo ""
+echo "The tar file will be created from the contents of "
+echo "${temp_dir}"
+echo "(which can now be examined or tweaked from another shell/window)"
+echo ""
+echo -n "Create gzipped tar file ${ctar_file} (y/n)? "
 set ans = $<
-set ctar_file = $ans/fer_environment.tar
-echo "Ready to create gzipped tar file $ctar_file"
-ready:
-echo "OK to continue ?"
-set ans = $<
-switch($ans)
-case y:
-   breaksw
-case n:
-   exit 0
-default:
-   echo "must answer y or n"
-   goto ready
-endsw
+while ( ("${ans}" != "y") && ("${ans}" != "n") )
+   echo -n "Answer either y or n: "
+   set ans = $<
+end
+if ( "${ans}" == "y" ) then
+   echo ""
+   rm -f "${ctar_file}"
+   tar cvzf "${ctar_file}" --exclude .svn *
+   echo ""
+   ls -l "${ctar_file}"
+else
+   echo ""
+   echo "Tar file NOT created"
+endif
 
-# make the gzipped tar file
-cd $source_dir
-rm -f .tar_create_log
-tar vcf $ctar_file  --exclude .svn *  >& ./tar_create_log
-gzip $ctar_file
-ls -l $ctar_file*
-echo "If there are any problems w/ the tar file, see "$source_dir/".tar_create_log for"
-echo "more information"
-
-
-
+# Clean up
+echo ""
+echo "Cleaning up - removing ${temp_dir}"
+cd "${target_dir}"
+rm -fr "${temp_dir}"
+echo ""
 
diff --git a/bin/make_executable_tar b/bin/make_executable_tar
--- a/bin/make_executable_tar
+++ b/bin/make_executable_tar
@@ -1,52 +1,162 @@
-#! /bin/csh -x
-# make_executable_tar
-# ver 1.0 5/99 *kob* 
+#! /bin/csh
 
-# this script encourages the tar file producer to make several manual
-# sanity checks but it does not enforce behavior
+# mycp needs to recursively copy subdirectories for the lib/python* directories
+set mycp = "/bin/cp -v -r --preserve=timestamp"
+set mylns = "/bin/ln -v -s"
 
-if ( $#argv == 1 ) then
-   set targ_dist_parent = $argv[1]
-   set bin_dir = $targ_dist_parent
-else
-   echo usage:
-   echo "         make_environment_tar binary_area machine_type "
-   echo e.g. "'make_executable_tar /home/users/ansley/ferret_install_utilities/bin'"
-   echo will make a gzipped tar file with the Ferret executables that are 
-   echo in the /home/users/ansley/ferret_install_utilities/bin directory  
-   exit 0
+echo ""
+if ( ($#argv < 2) || ($#argv > 3)  ) then
+   echo "Usage:  $0  <ferret_dir>  [ <pyferret_install_dir> ] <target_dir> "
+   echo ""
+   echo "    The required files will be copied from the ferret source directory "
+   echo "    <ferret_dir>, in which ferret or pyferret, gksm2ps, and the font files "
+   echo "    have been built.  If this is a build of pyferret, <pyferret_install_dir> "
+   echo "    should also be given as the installation directory for pyferret (e.g., "
+   echo '    $FER_DIR).  All lib/python* subdirectories of this directory will be '
+   echo "    copied.  All the files required will be copied to a temporary directory "
+   echo "    which this script will create.  Any missing executables will be noted. "
+   echo "    The file fer_executables.tar.gz will be written in <target_dir>, which "
+   echo "    must already exist. "
+   echo ""
+   exit 1
 endif
 
-cd $bin_dir
+if ( ! -d "$1" ) then
+   echo "$1 does not exist or is not a directory"
+   echo ""
+   exit 1
+endif
+set ferret_dir = `cd "$1" ; pwd`
+if ( ! -d "$2" ) then
+   echo "$2 does not exist or is not a directory"
+   echo ""
+   exit 1
+endif
+if ( $#argv == 2 ) then
+   set pyferret_dir = ""
+   set target_dir = `cd "$2" ; pwd`
+else
+   set pyferret_dir = `cd "$2" ; pwd`
+   if ( ! -d "$3" ) then
+      echo "$3 does not exist or is not a directory"
+      echo ""
+      exit 1
+   endif
+   set target_dir = `cd "$3" ; pwd`
+endif
 
-# get tar file location
-echo "Enter directory path to create the gzipped tar file in"
+# Get the version of ferret recorded in the code
+set version = `awk '/revision_level/ {print $4}' ${ferret_dir}/fer/dat/xrevision_data.F`
+if ( ($status != 0) || ("${version}" == "") ) then
+   echo "Unable to read the version number from xrevision_data.F in ${ferret_dir}/fer/dat"
+   echo ""
+   exit 1
+endif
+echo "Ferret version number is ${version}"
+echo ""
+
+# Make a clean temporary directory for the tar file contents
+set temp_dir = "/var/tmp/fer_exe_$$"
+rm -fr ${temp_dir}
+mkdir ${temp_dir}
+
+mkdir ${temp_dir}/bin
+
+# Copy fer/ferret_c
+if ( -x ${ferret_dir}/fer/ferret_c ) then
+   ${mycp} ${ferret_dir}/fer/ferret_c ${temp_dir}/bin/ferret_v${version}
+   cd ${temp_dir}/bin
+   ${mylns} ferret_v${version} ferret
+else 
+   echo "No ferret_c executable found in ${ferret_dir}/fer"
+#  An error only if pyferret_dir was not given
+   if ( "${pyferret_dir}" == "" ) then
+      echo ""
+      exit 1
+   else
+      echo "   ferret_v<n> and ferret symbolic link not created"
+      echo ""
+   endif
+endif
+
+# Copy gksm2ps/gksm2ps
+if ( ! -x ${ferret_dir}/gksm2ps/gksm2ps ) then
+   echo "No gksm2ps executable found in ${ferret_dir}/gksm2ps"
+   echo ""
+   exit 1
+endif
+${mycp} ${ferret_dir}/gksm2ps/gksm2ps ${temp_dir}/bin/gksm2ps
+
+# Copy font files from bin/build_fonts/unix/
+set fer_files = ${ferret_dir}/bin/build_fonts/unix/f*
+if ( ($status != 0) || ("${fer_files}" == "") ) then
+   echo "No font files found in ${ferret_dir}/bin/build_fonts/unix"
+   echo ""
+   exit 1
+endif
+mkdir ${temp_dir}/ppl
+mkdir ${temp_dir}/ppl/fonts
+${mycp} ${fer_files} ${temp_dir}/ppl/fonts
+
+# Copy fer/threddsBrowser/threddsBrowser.jar and 
+# fer/threddsBrowser/toolsUI/toolsUI*.jar
+set tb_jar = ${ferret_dir}/fer/threddsBrowser/threddsBrowser.jar
+if ( ! -r ${tb_jar} ) then
+   echo "No threddsBrowser.jar file found ${ferret_dir}/fer/threddsBrowser"
+   echo ""
+   exit 1
+endif
+set toolsui_jar = ${ferret_dir}/fer/threddsBrowser/toolsUI/toolsUI-*.jar
+if ( ($status != 0) || ("${toolsui_jar}" == "") ) then
+   echo "No toolsUI-*.jar file found in ${ferret_dir}/fer/threddsBrowser/toolUI"
+   echo ""
+   exit 1
+endif
+mkdir ${temp_dir}/lib
+${mycp} ${tb_jar} ${toolsui_jar} ${temp_dir}/lib
+cd ${temp_dir}/lib
+${mylns} toolsUI-*.jar toolsUI.jar
+
+# Copy pyferret files
+if ( "${pyferret_dir}" != "" ) then
+   set python_dirs = ${pyferret_dir}/lib/python*
+   if ( ($status != 0) || ("${python_dirs}" == "") ) then
+      echo "No python* directories found in ${pyferret_dir}/lib"
+      echo ""
+      exit 1
+   endif
+   ${mycp} ${python_dirs} ${temp_dir}/lib
+endif
+
+# Create the tar file
+set ctar_file = "${target_dir}/fer_executables.tar.gz"
+echo ""
+echo "The tar file will be created from the contents of "
+echo "${temp_dir}"
+echo "(which can now be examined or tweaked from another shell/window)"
+echo ""
+echo -n "Create gzipped tar file ${ctar_file} (y/n)? "
 set ans = $<
-set ctar_file = $ans/fer_executables.tar
-echo "Ready to create gzipped tar file $ctar_file"
-ready:
-echo "OK to continue ?"
-set ans = $<
-switch($ans)
-case y:
-   breaksw
-case n:
-   exit 0
-default:
-   echo "must answer y or n"
-   goto ready
-endsw
+while ( ("${ans}" != "y") && ("${ans}" != "n") )
+   echo -n "Answer either y or n: "
+   set ans = $<
+end
+if ( "${ans}" == "y" ) then
+   echo ""
+   cd ${temp_dir}
+   rm -f "${ctar_file}"
+   tar cvzf "${ctar_file}" *
+   echo ""
+   ls -l "${ctar_file}"
+else
+   echo ""
+   echo "Tar file NOT created"
+endif
 
-# make the gzipped tar file
-rm -f .tar_create_log
-tar vcf $ctar_file * >& $bin_dir/.tar_create_log
-
-gzip $ctar_file
-
-ls -l $ctar_file.*
-echo "If there are any problems w/ the tar file, see "$bin_dir/".tar_create_log for"
-echo "more information"
-
-
-
+# Clean up
+echo ""
+echo "Cleaning up - removing ${temp_dir}"
+cd "${target_dir}"
+rm -fr "${temp_dir}"
+echo ""
 
diff --git a/bin/make_source_tar b/bin/make_source_tar
--- a/bin/make_source_tar
+++ b/bin/make_source_tar
@@ -1,66 +1,85 @@
-#! /bin/csh -x
-# make_source_tar
-# ver 1.0 6/10 *acm*
-# ver 2.0 11/10 *acm* change CVS to svn
+#! /bin/csh
 
-# this script gets the source code, asking for any particular tag, or for trunk
-
-if ( $#argv == 2 ) then
-   set targ_dist_parent = $argv[1]
-   set tag = $argv[2]
-   set source_dir = $targ_dist_parent
-else
+if ( $#argv != 2 ) then
+   echo "Usage:  $0  <svn_repository>  <target_dir> "
    echo ""
-   echo usage:
-   echo make_source_tar target_area tag
-   echo   OR make_source_tar target_area trunk
-   echo e.g. "'make_source_tar /home/users/tmap/ferret v6_6_2_release'" will make a 
-   echo gzipped tar file of the corresponding Ferret source in the directory
-   echo "'/home/users/tmap/ferret/v6_6_2_release'"
-   echo "use HEAD if no tag or branch to be used"
+   echo "    The required files will be extracted from <svn_repository> "
+   echo "    (e.g., 'file:///home/users/tmap/svn/repos/ferret/trunk') "
+   echo "    to a temporary directory which this script will create. "
+   echo "    The gzipped tar file fer_source.tar.gz will be written in "
+   echo "    <target_dir>, which must already exist. "
    echo ""
- exit 0
+   exit 1
 endif
 
-cd $source_dir
-mkdir $tag
-cd $tag
-
-#use svn now to checkout desired files
-echo "Extracting FERRET source code......."
-
-if ( $tag == trunk ) then
-   svn checkout file:///home/users/tmap/svn/repos/ferret/trunk FERRET >&! .install_log
-else
-   svn checkout file:///home/users/tmap/svn/repos/ferret/tags/$tag FERRET >&! .install_log
+set info = `svn info "$1"`
+if ( "${info}" == "" ) then
+#  svn has printed an appropriate error message
+#  (but still returned a zero status)
+   echo ""
+   exit 1
 endif
-cp ./FERRET/fer/README ./FERRET
+set repository = "$1"
 
-# get tar file location
-set ctar_file = fer_source.tar
-echo "Ready to create gzipped tar file $ctar_file"
-ready:
-echo "OK to continue ?"
+if ( ! -d "$2" ) then
+   echo "$2 does not exist or is not a directory "
+   echo ""
+   exit 1
+endif
+# Make sure target_dir is a full pathname
+set target_dir = `cd "$2" ; pwd`
+
+# Decide what to call the directory checked-out from svn
+set fer_name = ${repository:t}
+if ( ${fer_name} == "trunk" ) then
+   set datestamp = `date +%F`
+   set fer_name = "ferret_${datestamp}"
+else if ( ${fer_name} == "pyferret" ) then
+   set datestamp = `date +%F`
+   set fer_name = "pyferret_${datestamp}"
+endif
+
+# Make a clean temporary directory for the tar file contents
+set temp_dir = "/var/tmp/fer_src_$$"
+rm -fr ${temp_dir}
+mkdir ${temp_dir}
+cd ${temp_dir}
+
+# Checkout the required files
+echo "Extracting FERRET source code "
+echo "from ${repository} "
+echo "to ${temp_dir}/${fer_name} "
+svn checkout -q ${repository} ${fer_name}
+
+# Create the tar file
+set ctar_file = "${target_dir}/fer_source.tar.gz"
+echo ""
+echo "The tar file will be created from the contents "
+echo "(except for the .svn subdirectories) of "
+echo "${temp_dir}"
+echo "(which can now be examined or tweaked from another shell/window)"
+echo ""
+echo -n "Create gzipped tar file ${ctar_file} (y/n)? "
 set ans = $<
-switch($ans)
-case y:
-   breaksw
-case n:
-   exit 0
-default:
-   echo "must answer y or n"
-   goto ready
-endsw
+while ( ("${ans}" != "y") && ("${ans}" != "n") )
+   echo -n "Answer either y or n: "
+   set ans = $<
+end
+if ( "${ans}" == "y" ) then
+   echo ""
+   rm -f "${ctar_file}"
+   tar cvzf "${ctar_file}" --exclude .svn "${fer_name}"
+   echo ""
+   ls -l "${ctar_file}"
+else
+   echo ""
+   echo "Tar file NOT created"
+endif
 
-# make the gzipped tar file
-cd $source_dir/$tag
-rm -f .tar_create_log
-tar vcf $ctar_file  --exclude .svn .  >& ./tar_create_log
-gzip $ctar_file
-ls -l $ctar_file*
-echo "If there are any problems w/ the tar file, see "$source_dir/".tar_create_log for"
-echo "more information"
-
-
-
+# Clean up
+echo ""
+echo "Cleaning up - removing ${temp_dir}"
+cd "${target_dir}"
+rm -fr "${temp_dir}"
+echo ""
 
